services:
  conduit_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: conduit
    volumes:
      - postgres:/var/lib/postgresql/data
    container_name: "some-postgres"

  app:
    build:
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    container_name: "conduit"
    depends_on:
      - conduit_db

volumes:
  postgres: