### GET request to example server
GET http://localhost:8080/api/articles/title-1/comments
Authorization: Bearer

###
POST http://localhost:8080/api/articles/title-1/comments
Authorization: Bearer
Content-Type: application/json

{
  "comment": {
    "body": "Comment 2"
  }
}

###
DELETE http://localhost:8080/api/articles/title-1/comments/1
Authorization: Bearer
